### PR TITLE
Fix: MessageDlg displayed several times due to the timer

### PR DESCRIPTION
**Pull request by romnGit**
Add: Log messages every 60s while waiting pid's shutdown

### CODE REVIEW

**Comment by Thynix** [comment]
Whoops! I have no idea why I didn't notice this. Sorry! It's now on my list of things to review.

**Comment by Thynix** [comment]
Thanks!

**Comment by Thynix** [comment]
I notice the messages are only in English. Do you know if GetText's Pascal support is any good?

**Comment by romnGit** [comment]
Oh, i though this project was abandoned !
Yes, programs in object pascal can be [internationalized](http://wiki.freepascal.org/Translations_/_i18n_/_localizations_for_programs). However, my tests for program internationalization are limited and it's a part i still need to dig.

To be honest, i don't want to be the "only" maintainer for this project anymore (i'm not reliable enough). So if you want to get rid of this an implement it in a language you are more familiar with go ahead.

Since, I don't remember precisely all the details of this project but the Innosetup installer could be used as an updater too.

**Comment by Thynix** [comment]
I'm sorry - new features are low priority with 1468 being delayed for as long as it has.

Okay, I'll look into adding updater support to the C# Windows tray.

**Comment by romnGit** [comment]
No worries ! There is no blame intended in my previous answer ;) .
The poor decision of jumping in this project with a language with ~~few~~ no other potential maintainers is mine not yours .

Good luck for your C# implementation :+1:

**Pull request merged**
